# Generated by Django 5.0.2 on 2024-03-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_tag_adverts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adverts',
            new_name='Advert',
        ),
    ]
