# Generated by Django 5.0.2 on 2024-03-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_adverts_advert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='AdOwner',
        ),
    ]
