# Generated by Django 5.0.2 on 2024-03-02 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_advert_adowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='AdOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
