# Generated by Django 5.0.2 on 2024-04-16 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_advert_adpay_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserComment', models.TextField()),
                ('CommentTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('CommentedAdvert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='API.advert')),
            ],
        ),
    ]
